description: Massachusetts assign these values as the standard_assistance for households size of 1. 
metadata:
  unit: /1
  label: Massachusetts EAEDC standard_assistance base
  breakdown:
  - ma_eaedc_living_arrangement 
  reference:
    - title: Emergency Aid to the Elderly Disabled and Children (EAEDC) Living Arrangement
      href: https://www.mass.gov/lists/emergency-aid-to-the-elderly-disabled-and-children-eaedc-living-arrangement
    - title: Emergency Aid to the Elderly Disabled and Children (EAEDC) Grant Calculation
      href: https://www.mass.gov/lists/emergency-aid-to-the-elderly-disabled-and-children-eaedc-grant-calculation

A:
  2022-01-01: 401
B:
  2022-01-01: 121
C:
  2022-01-01: 72.8
D:
  2022-01-01: 401
E:
  2022-01-01: 72.8
F:
  2022-01-01: 258
H:
  2022-01-01: 267.3
