description: New York provides this base amount for the child tax credit per child.
values:
  2018-01-01: 1_000
metadata:
  unit: currency-USD
  period: year
  label: New York CTC base amount
  reference:
    - title: Instructions for Form IT-213 Claim for Empire State Child Credit
      href: https://www.tax.ny.gov/pdf/2021/inc/it213i_2021.pdf#page=2
