description: Kentucky gross income adjustments sources.
values:
  2023-01-01:
    - ky_filing_status


metadata:
  unit: variable
  label: kentucky gross income adjustments sources
  reference:
  - title: Do I Need to File a Return
    href: https://revenue.ky.gov/Individual/Individual-Income-Tax/Pages/Do-I-Need-to-File-a-Return.aspx