description: Hawaii provides this base exemption amount.
values:
  2021-01-01: 1_144

metadata:
  period: year
  unit: currency-USD
  label: "Hawaii exemption base amount"
  reference:
  - title: 2022 Hawaii Resident Income Tax Instructions #page 20, line 25
    href: https://files.hawaii.gov/tax/forms/2022/n11ins.pdf#page=20
  - title: 2021 Hawaii Resident Income Tax Instructions #page 20, line 25
    href: https://files.hawaii.gov/tax/forms/2021/n11ins.pdf#page=20

  
