description: Kentucky modified gross income sources.
values:
  2023-01-01:
    - ky_family_size



metadata:
  unit: variable
  label: Kentucky modified gross income sources
  reference:
  - title: Do I Need to File a Return
    href: https://revenue.ky.gov/Individual/Individual-Income-Tax/Pages/Do-I-Need-to-File-a-Return.aspx
