description: Kentucky modified gross income sources.
values:

brackets:
  - threshold:
      2023-01-01: 0
    amount:
      2023-01-01: 0
  - threshold:
      2023-01-01: 1
    amount:
      2023-01-01: 13_590
  - threshold:
      2023-01-01: 2
    amount:
      2023-01-01: 18_310
  - threshold:
      2023-01-01: 3
    amount:
      2023-01-01: 23_030
  - threshold:
      2023-01-01: 4
    amount:
      2023-01-01: 27_750

metadata:
  type: single_amount
  threshold_unit: family-size
  amount_unit: currency-USD
  label: Kentucky modified gross income sources
  reference:
  - title: Do I Need to File a Return
    href: https://revenue.ky.gov/Individual/Individual-Income-Tax/Pages/Do-I-Need-to-File-a-Return.aspx