description: The IRS limits the expense of west region operating costs by the local standards to this amount, based on the number of owned vehicle, under the Chapter 7 Bankruptcy means test.

West_region:
  1:
    2024-01-01: 273
  2:
    2024-01-01: 546
Anchorage:
  1:
    2024-01-01: 200
  2:
    2024-01-01: 400
Denver:
  1: 
    2024-01-01: 321
  2:
    2024-01-01: 642
Honolulu:
  1:
    2024-01-01: 254
  2:
    2024-01-01: 508
Los_Angeles:
  1:
    2024-01-01: 331
  2:
    2024-01-01: 662
Phoenix:
  1: 
    2024-01-01: 300
  2:
    2024-01-01: 600
San_Diego:
  1:
    2024-01-01: 310
  2:
    2024-01-01: 620
San_Francisco:
  1:
    2024-01-01: 348
  2:
    2024-01-01: 696
Seattle:
  1: 
    2024-01-01: 271
  2:
    2024-01-01: 542

metadata:
  unit: currency-USD
  period: year
  label: Local standards of operating costs amount
  breakdown:
  - west_county
  - list(range(1,3))
  reference:
    - title: Local standards -- Transportation
      href: https://www.irs.gov/businesses/small-businesses-self-employed/local-standards-transportation
