description: New York provides cash assistance for each individual living under the poverty line of this amount, under Scott Budow's end entrenched poverty proposal.
metadata:
  type: single_amount
  threshold_unit: /1
  amount_unit: currency-USD
  period: year
  label: New York Scott Budow end entrenched poverty base amount
  reference:
    - title: Scott Budow End Entrenched Poverty
      href: https://www.scottbudow.com/issues?id=f5b39b46-f3ca-4fc8-a546-9229dbfbd487
brackets:
  - threshold:
      2022-01-01: 0
    amount:
      2022-01-01: 0 # proposal includes $1200 ($100 per month)
  - threshold:
      2022-01-01: 2
    amount:
      2022-01-01: 0

