description: Massachusetts provides the Transitional Aid to Families with Dependent Children program to families in private housing with gross income below this limit, based on family size.

metadata:
  type: single_amount
  period: month
  threshold_unit: int
  amount_unit: currency-USD
  label: Massachusetts TAFDC private household eligibility limit base amount 
  reference:
  - title: 2021 TAFDC and EAEDC Benefit increase Report
    href: https://www.mass.gov/doc/tafdc-and-eaedc-benefit-increase-report/download#:~:text=In%20response%20to%20COVID%2D19,by%2010%25%20effective%20January%201.
  - title: 2022 Transitional Aid to Families with Dependent Children Consolidated Report
    href: https://www.mass.gov/doc/tafdc-consolidated-report-march-2022/download
  - title: 2023 Transitional Aid to Families with Dependent Children Consolidated Report
    href: https://www.mass.gov/doc/tafdc-consolidated-report-march-2022/download

brackets:
  - threshold:
      2021-01-01: 0
    amount:
      2021-01-01: 467
      2022-01-01: 506
      2023-01-01: 2_510
  - threshold:
      2021-01-01: 2
    amount:
      2021-01-01: 580
      2022-01-01: 629
      2023-01-01: 3_407
  - threshold:
      2021-01-01: 3
    amount:
      2021-01-01: 692
      2022-01-01: 753
      2023-01-01: 4_303
  - threshold:
      2021-01-01: 4
    amount:
      2021-01-01: 800
      2022-01-01: 869
      2023-01-01: 5_200
  - threshold:
      2021-01-01: 5
    amount:
      2021-01-01: 911
      2022-01-01: 990
      2023-01-01: 6_097
  - threshold:
      2021-01-01: 6
    amount:
      2021-01-01: 1_026
      2022-01-01: 1_115
      2023-01-01: 6_993
  - threshold:
      2021-01-01: 7
    amount:
      2021-01-01: 1_137
      2022-01-01: 1_236
      2023-01-01: 7_890
  - threshold:
      2021-01-01: 8
    amount:
      2021-01-01: 1_247
      2022-01-01: 1_356
      2023-01-01: 8_787
