description: North Dakota adds these variables to US taxable income when computing its taxable income.
values:
  2021-01-01:
    - form_4972_lumpsum_distributions

metadata:
  unit: variable
  label: North Dakota additions to US taxable income
  reference:
  - title: 2021 ND income tax form
    href: https://www.tax.nd.gov/sites/www/files/documents/forms/individual/2021-iit/form-nd-1-2021.pdf#page=1
  - title: 2021 ND income tax instructions, line 2
    href: https://www.tax.nd.gov/sites/www/files/documents/forms/individual/2021-iit/individual-income-tax-booklet-2021.pdf#page=14
  - title: 2022 ND income tax form
    href: https://www.tax.nd.gov/sites/www/files/documents/forms/individual/2022-iit/form-nd-1-2022.pdf#page=1
  - title: 2022 ND income tax instructions, line 2
    href: https://www.tax.nd.gov/sites/www/files/documents/forms/individual/2022-iit/2022-individual-income-tax-booklet#page=14
  
