description: California limits the CalWORKs Child Care to filers with property value below this amount in a household with no aged or disabled members.

values:
  2023-01-01: 10_888

metadata:
  unit: currency-USD
  period: year
  label: California CalWORKs Child Care base property value limit
  reference:
  - title: Los Angeles Department DPSS CalWORKs
    href: https://dpss.lacounty.gov/en/cash/calworks.html
