description: Puerto Rico accounts for the following investment income sources, under the earned income tax credit. 
values:
  2023-01-01: 
  - interest_income
  - dividend_income
  - rental_income
  - capital_gains
  - child_support_received
metadata:
  unit: list
  period: year
  label: Puerto Rico earned income credit investment income sources
  reference:
    - title: P.R. Laws tit. 13, ยง 30211 (e)
      href: https://casetext.com/statute/laws-of-puerto-rico/title-thirteen-taxation-and-finance/subtitle-17-internal-revenue-code-of-2011/part-ii-income-taxes/chapter-1007-credits-against-tax/subchapter-b-refundable-credits/30211-earned-income-credit
    - title: Schedule CT Individual, Earned Income Credit, 2023
      href: https://hacienda.pr.gov/sites/default/files/schedule_ct_rev._jul_5_23_informative_-_instructions.pdf#page=4