description: Nebraska limits the child care subsidy to children of this age or younger, not requiring special needs care.  
values:
  2021-08-28: 12
metadata:
  period: year
  unit: year
  label: Nebraska child care subsidy base age threshold
  reference:
    # Age threshold not mentioned in legal code
    - title: Nebraska Revised Statute | Chapter 77 | ยง7202 (1)
      href: https://nebraskalegislature.gov/laws/statutes.php?statute=77-7202
    - title: Nebraska DHHS, Child Care Subsidy Information For Parents
      href: https://dhhs.ne.gov/Pages/Child-Care-Subsidy-Information-for-Parents.aspx
